### ISSUE TITLE
Unable to create empty vector

### ISSUE THREAD

**Issue by jkocot** [diffplug/matfilerw#17]
I would like to create a MLDouble object from an empty array (or empty list) - meaning that it should be represented by '[]' in Matlab and its size(empty,1) should return 0. I tried:
 - new MLDouble(varName, new int[0]) - this throws:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.jmatio.types.MLArray.getM(MLArray.java:126)
	at com.jmatio.types.MLArray.getSize(MLArray.java:142)
	at com.jmatio.types.MLNumericArray.allocate(MLNumericArray.java:44)
	at com.jmatio.types.MLNumericArray.<init>(MLNumericArray.java:40)
	at com.jmatio.types.MLDouble.<init>(MLDouble.java:37)
```
 - new MLDouble(varName, new double[0], 0) throws:
```
java.lang.ArithmeticException: / by zero
	at com.jmatio.types.MLNumericArray.<init>(MLNumericArray.java:64)
	at com.jmatio.types.MLDouble.<init>(MLDouble.java:49)
	at com.jmatio.types.MLDouble.<init>(MLDouble.java:74)
```
- new MLDouble(varName, new double[0][0]) throws:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.jmatio.types.MLDouble.double2DToDouble(MLDouble.java:123)
	at com.jmatio.types.MLDouble.<init>(MLDouble.java:62)
```
 - new MLDouble(varName, new double[0], 1) works, but size(empty,1) returns 1, which is unexpected, and my Matlab code fails

**Comment by jkocot** [comment]
I also tried using ``new MLEmptyArray(varName)``, but this throws the error below when writing the object:
```
java.lang.ClassCastException: com.jmatio.types.MLEmptyArray cannot be cast to com.jmatio.types.MLNumericArray
	at com.jmatio.io.MatFileWriter.writeMatrix(MatFileWriter.java:291)
	at com.jmatio.io.MatFileWriter.writeMatrix(MatFileWriter.java:402)
	at com.jmatio.io.MatFileWriter.write(MatFileWriter.java:196)
	at com.jmatio.io.MatFileWriter.write(MatFileWriter.java:164)
```

**Comment by nedtwigg** [comment]
How about `new MLDouble("name", new int[]{0, 0});`

**Comment by nedtwigg** [comment]
Feel free to reopen if you have more to discuss.

**Comment by jkocot** [comment]
Yep, `new MLDouble("name", new int[]{0, 0});` works. Thanks.

Maybe it would be useful to update the documentation (javadoc) with an information how to do this. MLEmptyArray really looked like a good guess, but it clearly is for something else...
