### ISSUE TITLE
Unknown data type 17 in MAT file cannot be parsed

### ISSUE THREAD

**Issue by draeger** [diffplug/matfilerw#2]
I am trying to parse the file `iAH991.mat` that I have downloaded from http://wwwen.uni.lu/lcsb/research/mol_systems_physiology/in_silico_models. Here is the direct link to a ZIP archive that contains this file
http://wwwen.uni.lu/content/download/72941/917467/file/Bacteroides%20thetaiotaomicron..mat.zip

When reading this file with 
```Java 
MatFileReader mfr = new MatFileReader(new File("~/iAH991.mat"));
```
this results in
```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown data type: 17
	at com.jmatio.io.stream.MatFileInputStream.readByte(MatFileInputStream.java:144)
	at com.jmatio.io.MatFileReader$ISMatTag.readToByteArray(MatFileReader.java:1395)
	at com.jmatio.io.MatFileReader$ISMatTag.readToString(MatFileReader.java:1434)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:1068)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:927)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:911)
	at com.jmatio.io.MatFileReader.readData(MatFileReader.java:806)
	at com.jmatio.io.MatFileReader.readData(MatFileReader.java:794)
	at com.jmatio.io.MatFileReader.parseData(MatFileReader.java:408)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:371)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:309)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:170)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:146)
```
Any help is appreciated.

**Comment by nedtwigg** [comment]
A-ha!  We've been working off of the MAT-File spec from 2012b (in [doc/matfile_format.pdf](doc/matfile_format.pdf)).  Looking at the [R2015b spec](https://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf), it looks like they've added UTF8, UTF16, and UTF32 fields as built-in datatypes.  Should be a pretty straight-forward case of adding another entry to the giant switch/case in MatFileReader and Writer.

I should be able to get to it by Wednesday, or I'd be happy to help you work on it.

**Comment by draeger** [comment]
Thanks for this help! Wednesday would be great.

**Comment by nedtwigg** [comment]
2.1.0 has shipped with a fix (a day late).  Feel free to reopen if you encounter any further issues.

**Comment by draeger** [comment]
Great! It works. Thanks!
