### ISSUE TITLE
It is impossible to call MatFileReader.read(File file) twice

### ISSUE THREAD

**Issue by smagellan** [diffplug/matfilerw#20]
Second call to read(File) produces this:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:315)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:308)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:239)
	at com.smagellan.toyml.Main.main(Main.java:20)
```

**Comment by nedtwigg** [comment]
Published in 3.1.1, thanks for the fix!
